travis:
  secure:
    BINSTAR_TOKEN: M2qmsxvbRu2EJwbB7kWgS14ZH8zJoalhR4OslHk4LVUNcy8k+BNIK+TQJr52DrWqYteQ0I0czsuV4NrSVVeiJBMvIgc6eONVZeZC8AASR5noRP09TPa8C5BLq4tKakH1Zl5bmWRQG4LReN/hDbpPhow39MOpmeS6z7x4J6fU/KvgBDBXJJiNeZPg9EBMZ0kBbc0xCl8W7ah7HjOj8y09leNpQ5lllLOv3aW8vV9bRd7Pc7wj9/86ILmqUueZCiH0KGtQRzAXyzbjX5bTQxiHuJgeHlc3Q8JKOyOU7h8ganQfpFT5DeXInOBC8vy5rOxV983Uzls39YjR73iy9rDKj+AXyUHqc1sJ9CRXtk13q2DRXBhFd1YjhMUnH2zp+IR0pSu1AQSRtF6mW2pxEXt/6M3KaLzPGU/RgKNfjWpWOjD+xjZONYY5FiMFi5ZzkHDKM346EYW8S70CPTdLQJ/9QtYZmwIIGp/OXbyf3GuNSVtihnV9KHzlNeR3nz8Hd6ShS+ZzvKawM4Srs8PY33JtoVvkSUJeWm9UTS7wJ9Y51HyjstxZGhhzgxITOo/DmfNdRvlgN75OhXH8z5GCBVt8FiAyi6+Y0ZC2/U6ATlMbqIDvspG2Nw1LpIkkCTfyJdB73z+qOl5Yx5NP2c+g3SunqVDb5Lh8QH6irPkt3NueJmQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
