travis:
  secure:
    BINSTAR_TOKEN: fN6BGA3mxl+eOKcz6d5RuljiCDIkqJqNN0c19lH0ylGEEs1EWByMBLV6Q8NcACq/8Zk08D0V+jNKvZVPHY8+4BoydAidXOuNSghnipU+aqdAOOinR879g8x/jlwGHZJ4okdLoWuvBWStccKdJ0PfrhmKFnAjyegeNT81z0M1spfQ//vGly7/Dcsa7mCww7XwxIFx2d3cafIxZ6iN6a3YHmfZdz2iDd9w6HMX3kVLBGAbZG6acn9yP9Q5EnLD7kvgQN3NhwedrOlyzrwNJav6Ftvdoqlr1txDRCyg5/VWeEUsvSIfS7B3MTO8yVCU/SHYIMxvWz6K1STIkE0ZkS9vt8eicmDmBe895D+7huO2Mr3cHqEI5QeLxoh5MT/+M2LlSZNDoRzdovydTpsv+8SQrZqKkMpdGOb2jqtnoRBNmTSTKnCILpZJNFy1GdpTgnOJ1LTBOOox/BRUddZiDtg913Aaixs2uquQhN3xSxZCiyRHcWBoXuk37FQ+YokNFLx12eqwGCWpPlQUk7ATzMHNZHHjvPf0UtuwqJsFHHNjM8HBy+qTOdmY/ECdo9r0K5echHeCVJTXL6xuQlADsX+KWQBtsQUECL7brnKIWexmSORinmigqs4IbAjY3FDHr7DQsaDjan6my/2OXdNCzEIsfZr+AR1/qs2fkHiT7CdRzrY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
